# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Programs\CMake\bin\cmake.exe

# The command to remove a file.
RM = D:\Programs\CMake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\User\Desktop\Game Dev\knapsack-plus-plus"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\User\Desktop\Game Dev\knapsack-plus-plus"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\Programs\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\Programs\CMake\bin\cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\User\Desktop\Game Dev\knapsack-plus-plus\CMakeFiles" "D:\User\Desktop\Game Dev\knapsack-plus-plus\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\User\Desktop\Game Dev\knapsack-plus-plus\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named knapsackpp

# Build rule for target.
knapsackpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 knapsackpp
.PHONY : knapsackpp

# fast build rule for target.
knapsackpp/fast:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/build
.PHONY : knapsackpp/fast

src/audio/audio.obj: src/audio/audio.cpp.obj

.PHONY : src/audio/audio.obj

# target to build an object file
src/audio/audio.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/audio/audio.cpp.obj
.PHONY : src/audio/audio.cpp.obj

src/audio/audio.i: src/audio/audio.cpp.i

.PHONY : src/audio/audio.i

# target to preprocess a source file
src/audio/audio.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/audio/audio.cpp.i
.PHONY : src/audio/audio.cpp.i

src/audio/audio.s: src/audio/audio.cpp.s

.PHONY : src/audio/audio.s

# target to generate assembly for a file
src/audio/audio.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/audio/audio.cpp.s
.PHONY : src/audio/audio.cpp.s

src/ecs/component.obj: src/ecs/component.cpp.obj

.PHONY : src/ecs/component.obj

# target to build an object file
src/ecs/component.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/ecs/component.cpp.obj
.PHONY : src/ecs/component.cpp.obj

src/ecs/component.i: src/ecs/component.cpp.i

.PHONY : src/ecs/component.i

# target to preprocess a source file
src/ecs/component.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/ecs/component.cpp.i
.PHONY : src/ecs/component.cpp.i

src/ecs/component.s: src/ecs/component.cpp.s

.PHONY : src/ecs/component.s

# target to generate assembly for a file
src/ecs/component.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/ecs/component.cpp.s
.PHONY : src/ecs/component.cpp.s

src/engine.obj: src/engine.cpp.obj

.PHONY : src/engine.obj

# target to build an object file
src/engine.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/engine.cpp.obj
.PHONY : src/engine.cpp.obj

src/engine.i: src/engine.cpp.i

.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s

.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/entity/entity.obj: src/entity/entity.cpp.obj

.PHONY : src/entity/entity.obj

# target to build an object file
src/entity/entity.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/entity.cpp.obj
.PHONY : src/entity/entity.cpp.obj

src/entity/entity.i: src/entity/entity.cpp.i

.PHONY : src/entity/entity.i

# target to preprocess a source file
src/entity/entity.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/entity.cpp.i
.PHONY : src/entity/entity.cpp.i

src/entity/entity.s: src/entity/entity.cpp.s

.PHONY : src/entity/entity.s

# target to generate assembly for a file
src/entity/entity.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/entity.cpp.s
.PHONY : src/entity/entity.cpp.s

src/entity/entitymanager.obj: src/entity/entitymanager.cpp.obj

.PHONY : src/entity/entitymanager.obj

# target to build an object file
src/entity/entitymanager.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/entitymanager.cpp.obj
.PHONY : src/entity/entitymanager.cpp.obj

src/entity/entitymanager.i: src/entity/entitymanager.cpp.i

.PHONY : src/entity/entitymanager.i

# target to preprocess a source file
src/entity/entitymanager.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/entitymanager.cpp.i
.PHONY : src/entity/entitymanager.cpp.i

src/entity/entitymanager.s: src/entity/entitymanager.cpp.s

.PHONY : src/entity/entitymanager.s

# target to generate assembly for a file
src/entity/entitymanager.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/entitymanager.cpp.s
.PHONY : src/entity/entitymanager.cpp.s

src/entity/hitbox.obj: src/entity/hitbox.cpp.obj

.PHONY : src/entity/hitbox.obj

# target to build an object file
src/entity/hitbox.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/hitbox.cpp.obj
.PHONY : src/entity/hitbox.cpp.obj

src/entity/hitbox.i: src/entity/hitbox.cpp.i

.PHONY : src/entity/hitbox.i

# target to preprocess a source file
src/entity/hitbox.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/hitbox.cpp.i
.PHONY : src/entity/hitbox.cpp.i

src/entity/hitbox.s: src/entity/hitbox.cpp.s

.PHONY : src/entity/hitbox.s

# target to generate assembly for a file
src/entity/hitbox.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/entity/hitbox.cpp.s
.PHONY : src/entity/hitbox.cpp.s

src/handler.obj: src/handler.cpp.obj

.PHONY : src/handler.obj

# target to build an object file
src/handler.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/handler.cpp.obj
.PHONY : src/handler.cpp.obj

src/handler.i: src/handler.cpp.i

.PHONY : src/handler.i

# target to preprocess a source file
src/handler.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/handler.cpp.i
.PHONY : src/handler.cpp.i

src/handler.s: src/handler.cpp.s

.PHONY : src/handler.s

# target to generate assembly for a file
src/handler.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/handler.cpp.s
.PHONY : src/handler.cpp.s

src/input/gamepad.obj: src/input/gamepad.cpp.obj

.PHONY : src/input/gamepad.obj

# target to build an object file
src/input/gamepad.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/gamepad.cpp.obj
.PHONY : src/input/gamepad.cpp.obj

src/input/gamepad.i: src/input/gamepad.cpp.i

.PHONY : src/input/gamepad.i

# target to preprocess a source file
src/input/gamepad.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/gamepad.cpp.i
.PHONY : src/input/gamepad.cpp.i

src/input/gamepad.s: src/input/gamepad.cpp.s

.PHONY : src/input/gamepad.s

# target to generate assembly for a file
src/input/gamepad.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/gamepad.cpp.s
.PHONY : src/input/gamepad.cpp.s

src/input/keyboard.obj: src/input/keyboard.cpp.obj

.PHONY : src/input/keyboard.obj

# target to build an object file
src/input/keyboard.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/keyboard.cpp.obj
.PHONY : src/input/keyboard.cpp.obj

src/input/keyboard.i: src/input/keyboard.cpp.i

.PHONY : src/input/keyboard.i

# target to preprocess a source file
src/input/keyboard.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/keyboard.cpp.i
.PHONY : src/input/keyboard.cpp.i

src/input/keyboard.s: src/input/keyboard.cpp.s

.PHONY : src/input/keyboard.s

# target to generate assembly for a file
src/input/keyboard.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/keyboard.cpp.s
.PHONY : src/input/keyboard.cpp.s

src/input/mouse.obj: src/input/mouse.cpp.obj

.PHONY : src/input/mouse.obj

# target to build an object file
src/input/mouse.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/mouse.cpp.obj
.PHONY : src/input/mouse.cpp.obj

src/input/mouse.i: src/input/mouse.cpp.i

.PHONY : src/input/mouse.i

# target to preprocess a source file
src/input/mouse.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/mouse.cpp.i
.PHONY : src/input/mouse.cpp.i

src/input/mouse.s: src/input/mouse.cpp.s

.PHONY : src/input/mouse.s

# target to generate assembly for a file
src/input/mouse.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/input/mouse.cpp.s
.PHONY : src/input/mouse.cpp.s

src/metaparse.obj: src/metaparse.cpp.obj

.PHONY : src/metaparse.obj

# target to build an object file
src/metaparse.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/metaparse.cpp.obj
.PHONY : src/metaparse.cpp.obj

src/metaparse.i: src/metaparse.cpp.i

.PHONY : src/metaparse.i

# target to preprocess a source file
src/metaparse.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/metaparse.cpp.i
.PHONY : src/metaparse.cpp.i

src/metaparse.s: src/metaparse.cpp.s

.PHONY : src/metaparse.s

# target to generate assembly for a file
src/metaparse.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/metaparse.cpp.s
.PHONY : src/metaparse.cpp.s

src/rendering/camera.obj: src/rendering/camera.cpp.obj

.PHONY : src/rendering/camera.obj

# target to build an object file
src/rendering/camera.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/camera.cpp.obj
.PHONY : src/rendering/camera.cpp.obj

src/rendering/camera.i: src/rendering/camera.cpp.i

.PHONY : src/rendering/camera.i

# target to preprocess a source file
src/rendering/camera.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/camera.cpp.i
.PHONY : src/rendering/camera.cpp.i

src/rendering/camera.s: src/rendering/camera.cpp.s

.PHONY : src/rendering/camera.s

# target to generate assembly for a file
src/rendering/camera.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/camera.cpp.s
.PHONY : src/rendering/camera.cpp.s

src/rendering/renderrequest.obj: src/rendering/renderrequest.cpp.obj

.PHONY : src/rendering/renderrequest.obj

# target to build an object file
src/rendering/renderrequest.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/renderrequest.cpp.obj
.PHONY : src/rendering/renderrequest.cpp.obj

src/rendering/renderrequest.i: src/rendering/renderrequest.cpp.i

.PHONY : src/rendering/renderrequest.i

# target to preprocess a source file
src/rendering/renderrequest.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/renderrequest.cpp.i
.PHONY : src/rendering/renderrequest.cpp.i

src/rendering/renderrequest.s: src/rendering/renderrequest.cpp.s

.PHONY : src/rendering/renderrequest.s

# target to generate assembly for a file
src/rendering/renderrequest.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/renderrequest.cpp.s
.PHONY : src/rendering/renderrequest.cpp.s

src/rendering/sprite.obj: src/rendering/sprite.cpp.obj

.PHONY : src/rendering/sprite.obj

# target to build an object file
src/rendering/sprite.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/sprite.cpp.obj
.PHONY : src/rendering/sprite.cpp.obj

src/rendering/sprite.i: src/rendering/sprite.cpp.i

.PHONY : src/rendering/sprite.i

# target to preprocess a source file
src/rendering/sprite.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/sprite.cpp.i
.PHONY : src/rendering/sprite.cpp.i

src/rendering/sprite.s: src/rendering/sprite.cpp.s

.PHONY : src/rendering/sprite.s

# target to generate assembly for a file
src/rendering/sprite.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/sprite.cpp.s
.PHONY : src/rendering/sprite.cpp.s

src/rendering/tileset.obj: src/rendering/tileset.cpp.obj

.PHONY : src/rendering/tileset.obj

# target to build an object file
src/rendering/tileset.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/tileset.cpp.obj
.PHONY : src/rendering/tileset.cpp.obj

src/rendering/tileset.i: src/rendering/tileset.cpp.i

.PHONY : src/rendering/tileset.i

# target to preprocess a source file
src/rendering/tileset.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/tileset.cpp.i
.PHONY : src/rendering/tileset.cpp.i

src/rendering/tileset.s: src/rendering/tileset.cpp.s

.PHONY : src/rendering/tileset.s

# target to generate assembly for a file
src/rendering/tileset.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/rendering/tileset.cpp.s
.PHONY : src/rendering/tileset.cpp.s

src/screen.obj: src/screen.cpp.obj

.PHONY : src/screen.obj

# target to build an object file
src/screen.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/screen.cpp.obj
.PHONY : src/screen.cpp.obj

src/screen.i: src/screen.cpp.i

.PHONY : src/screen.i

# target to preprocess a source file
src/screen.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/screen.cpp.i
.PHONY : src/screen.cpp.i

src/screen.s: src/screen.cpp.s

.PHONY : src/screen.s

# target to generate assembly for a file
src/screen.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/screen.cpp.s
.PHONY : src/screen.cpp.s

src/utils/fastmath.obj: src/utils/fastmath.cpp.obj

.PHONY : src/utils/fastmath.obj

# target to build an object file
src/utils/fastmath.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/fastmath.cpp.obj
.PHONY : src/utils/fastmath.cpp.obj

src/utils/fastmath.i: src/utils/fastmath.cpp.i

.PHONY : src/utils/fastmath.i

# target to preprocess a source file
src/utils/fastmath.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/fastmath.cpp.i
.PHONY : src/utils/fastmath.cpp.i

src/utils/fastmath.s: src/utils/fastmath.cpp.s

.PHONY : src/utils/fastmath.s

# target to generate assembly for a file
src/utils/fastmath.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/fastmath.cpp.s
.PHONY : src/utils/fastmath.cpp.s

src/utils/log.obj: src/utils/log.cpp.obj

.PHONY : src/utils/log.obj

# target to build an object file
src/utils/log.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/log.cpp.obj
.PHONY : src/utils/log.cpp.obj

src/utils/log.i: src/utils/log.cpp.i

.PHONY : src/utils/log.i

# target to preprocess a source file
src/utils/log.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/log.cpp.i
.PHONY : src/utils/log.cpp.i

src/utils/log.s: src/utils/log.cpp.s

.PHONY : src/utils/log.s

# target to generate assembly for a file
src/utils/log.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/log.cpp.s
.PHONY : src/utils/log.cpp.s

src/utils/particle.obj: src/utils/particle.cpp.obj

.PHONY : src/utils/particle.obj

# target to build an object file
src/utils/particle.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/particle.cpp.obj
.PHONY : src/utils/particle.cpp.obj

src/utils/particle.i: src/utils/particle.cpp.i

.PHONY : src/utils/particle.i

# target to preprocess a source file
src/utils/particle.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/particle.cpp.i
.PHONY : src/utils/particle.cpp.i

src/utils/particle.s: src/utils/particle.cpp.s

.PHONY : src/utils/particle.s

# target to generate assembly for a file
src/utils/particle.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/particle.cpp.s
.PHONY : src/utils/particle.cpp.s

src/utils/tween.obj: src/utils/tween.cpp.obj

.PHONY : src/utils/tween.obj

# target to build an object file
src/utils/tween.cpp.obj:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/tween.cpp.obj
.PHONY : src/utils/tween.cpp.obj

src/utils/tween.i: src/utils/tween.cpp.i

.PHONY : src/utils/tween.i

# target to preprocess a source file
src/utils/tween.cpp.i:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/tween.cpp.i
.PHONY : src/utils/tween.cpp.i

src/utils/tween.s: src/utils/tween.cpp.s

.PHONY : src/utils/tween.s

# target to generate assembly for a file
src/utils/tween.cpp.s:
	$(MAKE) -f CMakeFiles\knapsackpp.dir\build.make CMakeFiles/knapsackpp.dir/src/utils/tween.cpp.s
.PHONY : src/utils/tween.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... knapsackpp
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... src/audio/audio.obj
	@echo ... src/audio/audio.i
	@echo ... src/audio/audio.s
	@echo ... src/ecs/component.obj
	@echo ... src/ecs/component.i
	@echo ... src/ecs/component.s
	@echo ... src/engine.obj
	@echo ... src/engine.i
	@echo ... src/engine.s
	@echo ... src/entity/entity.obj
	@echo ... src/entity/entity.i
	@echo ... src/entity/entity.s
	@echo ... src/entity/entitymanager.obj
	@echo ... src/entity/entitymanager.i
	@echo ... src/entity/entitymanager.s
	@echo ... src/entity/hitbox.obj
	@echo ... src/entity/hitbox.i
	@echo ... src/entity/hitbox.s
	@echo ... src/handler.obj
	@echo ... src/handler.i
	@echo ... src/handler.s
	@echo ... src/input/gamepad.obj
	@echo ... src/input/gamepad.i
	@echo ... src/input/gamepad.s
	@echo ... src/input/keyboard.obj
	@echo ... src/input/keyboard.i
	@echo ... src/input/keyboard.s
	@echo ... src/input/mouse.obj
	@echo ... src/input/mouse.i
	@echo ... src/input/mouse.s
	@echo ... src/metaparse.obj
	@echo ... src/metaparse.i
	@echo ... src/metaparse.s
	@echo ... src/rendering/camera.obj
	@echo ... src/rendering/camera.i
	@echo ... src/rendering/camera.s
	@echo ... src/rendering/renderrequest.obj
	@echo ... src/rendering/renderrequest.i
	@echo ... src/rendering/renderrequest.s
	@echo ... src/rendering/sprite.obj
	@echo ... src/rendering/sprite.i
	@echo ... src/rendering/sprite.s
	@echo ... src/rendering/tileset.obj
	@echo ... src/rendering/tileset.i
	@echo ... src/rendering/tileset.s
	@echo ... src/screen.obj
	@echo ... src/screen.i
	@echo ... src/screen.s
	@echo ... src/utils/fastmath.obj
	@echo ... src/utils/fastmath.i
	@echo ... src/utils/fastmath.s
	@echo ... src/utils/log.obj
	@echo ... src/utils/log.i
	@echo ... src/utils/log.s
	@echo ... src/utils/particle.obj
	@echo ... src/utils/particle.i
	@echo ... src/utils/particle.s
	@echo ... src/utils/tween.obj
	@echo ... src/utils/tween.i
	@echo ... src/utils/tween.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

